# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Maintenance_design_osh.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1106, 771)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 360))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setMouseTracking(True)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icons8-support-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.95)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: qconicalgradient(cx:0.403, cy:1, angle:0, stop:0.448864 rgba(16, 100, 158, 241), stop:1 rgba(255, 255, 255, 255));\n"
"border-top-color: rgb(42, 106, 255);\n"
"border-color: rgb(0, 156, 0);\n"
"")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.timedate = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timedate.sizePolicy().hasHeightForWidth())
        self.timedate.setSizePolicy(sizePolicy)
        self.timedate.setMinimumSize(QtCore.QSize(300, 25))
        self.timedate.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.timedate.setFont(font)
        self.timedate.setStyleSheet("color: rgb(26, 255, 14);")
        self.timedate.setFrameShape(QtWidgets.QFrame.Box)
        self.timedate.setText("")
        self.timedate.setObjectName("timedate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.timedate)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.btn = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn.sizePolicy().hasHeightForWidth())
        self.btn.setSizePolicy(sizePolicy)
        self.btn.setMinimumSize(QtCore.QSize(20, 25))
        self.btn.setMaximumSize(QtCore.QSize(50, 50))
        self.btn.setCheckable(True)
        self.btn.setObjectName("btn")
        self.horizontalLayout_1.addWidget(self.btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem2)
        self.terminal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminal.sizePolicy().hasHeightForWidth())
        self.terminal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.terminal.setFont(font)
        self.terminal.setCheckable(False)
        self.terminal.setAutoDefault(False)
        self.terminal.setObjectName("terminal")
        self.horizontalLayout_1.addWidget(self.terminal)
        spacerItem3 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem3)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"gridline-color: rgb(0, 85, 255);\n"
"selection-color: rgb(85, 170, 0);")
        self.start.setObjectName("start")
        self.horizontalLayout_1.addWidget(self.start)
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit.sizePolicy().hasHeightForWidth())
        self.exit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("background-color: qconicalgradient(cx:0.914773, cy:0.79, angle:0, stop:0.164773 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qconicalgradient(cx:1, cy:0.329773, angle:0, stop:0.164773 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.exit.setObjectName("exit")
        self.horizontalLayout_1.addWidget(self.exit)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.SpanningRole, spacerItem4)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelLT5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLT5.sizePolicy().hasHeightForWidth())
        self.labelLT5.setSizePolicy(sizePolicy)
        self.labelLT5.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelLT5.setFont(font)
        self.labelLT5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelLT5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelLT5.setText("")
        self.labelLT5.setTextFormat(QtCore.Qt.AutoText)
        self.labelLT5.setScaledContents(True)
        self.labelLT5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLT5.setObjectName("labelLT5")
        self.gridLayout_4.addWidget(self.labelLT5, 9, 4, 1, 1)
        self.labelWT1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWT1.sizePolicy().hasHeightForWidth())
        self.labelWT1.setSizePolicy(sizePolicy)
        self.labelWT1.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelWT1.setFont(font)
        self.labelWT1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelWT1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelWT1.setText("")
        self.labelWT1.setTextFormat(QtCore.Qt.AutoText)
        self.labelWT1.setScaledContents(True)
        self.labelWT1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWT1.setObjectName("labelWT1")
        self.gridLayout_4.addWidget(self.labelWT1, 0, 2, 1, 1)
        self.labelWT2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWT2.sizePolicy().hasHeightForWidth())
        self.labelWT2.setSizePolicy(sizePolicy)
        self.labelWT2.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelWT2.setFont(font)
        self.labelWT2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelWT2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelWT2.setText("")
        self.labelWT2.setTextFormat(QtCore.Qt.AutoText)
        self.labelWT2.setScaledContents(True)
        self.labelWT2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWT2.setObjectName("labelWT2")
        self.gridLayout_4.addWidget(self.labelWT2, 0, 6, 1, 1)
        self.labelLT3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLT3.sizePolicy().hasHeightForWidth())
        self.labelLT3.setSizePolicy(sizePolicy)
        self.labelLT3.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelLT3.setFont(font)
        self.labelLT3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelLT3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelLT3.setText("")
        self.labelLT3.setTextFormat(QtCore.Qt.AutoText)
        self.labelLT3.setScaledContents(True)
        self.labelLT3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLT3.setObjectName("labelLT3")
        self.gridLayout_4.addWidget(self.labelLT3, 8, 6, 1, 1)
        self.labelLT4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLT4.sizePolicy().hasHeightForWidth())
        self.labelLT4.setSizePolicy(sizePolicy)
        self.labelLT4.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelLT4.setFont(font)
        self.labelLT4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelLT4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelLT4.setText("")
        self.labelLT4.setTextFormat(QtCore.Qt.AutoText)
        self.labelLT4.setScaledContents(True)
        self.labelLT4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLT4.setObjectName("labelLT4")
        self.gridLayout_4.addWidget(self.labelLT4, 9, 2, 1, 1)
        self.labelLT1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLT1.sizePolicy().hasHeightForWidth())
        self.labelLT1.setSizePolicy(sizePolicy)
        self.labelLT1.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelLT1.setFont(font)
        self.labelLT1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelLT1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelLT1.setText("")
        self.labelLT1.setTextFormat(QtCore.Qt.AutoText)
        self.labelLT1.setScaledContents(True)
        self.labelLT1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLT1.setObjectName("labelLT1")
        self.gridLayout_4.addWidget(self.labelLT1, 8, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 3, 4, 1, 1)
        self.lineInfo = QtWidgets.QLabel(self.centralwidget)
        self.lineInfo.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineInfo.setFont(font)
        self.lineInfo.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lineInfo.setText("")
        self.lineInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lineInfo.setObjectName("lineInfo")
        self.gridLayout_4.addWidget(self.lineInfo, 6, 2, 1, 5)
        self.labelCL2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCL2.sizePolicy().hasHeightForWidth())
        self.labelCL2.setSizePolicy(sizePolicy)
        self.labelCL2.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelCL2.setFont(font)
        self.labelCL2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelCL2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelCL2.setText("")
        self.labelCL2.setTextFormat(QtCore.Qt.AutoText)
        self.labelCL2.setScaledContents(True)
        self.labelCL2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCL2.setObjectName("labelCL2")
        self.gridLayout_4.addWidget(self.labelCL2, 5, 8, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 7, 4, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setProperty("value", 99)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 5, 3, 1, 3)
        self.labelCL3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCL3.sizePolicy().hasHeightForWidth())
        self.labelCL3.setSizePolicy(sizePolicy)
        self.labelCL3.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelCL3.setFont(font)
        self.labelCL3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelCL3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelCL3.setText("")
        self.labelCL3.setTextFormat(QtCore.Qt.AutoText)
        self.labelCL3.setScaledContents(True)
        self.labelCL3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCL3.setObjectName("labelCL3")
        self.gridLayout_4.addWidget(self.labelCL3, 6, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(80, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 2, 5, 1, 1)
        self.labelLT2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLT2.sizePolicy().hasHeightForWidth())
        self.labelLT2.setSizePolicy(sizePolicy)
        self.labelLT2.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelLT2.setFont(font)
        self.labelLT2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelLT2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelLT2.setText("")
        self.labelLT2.setTextFormat(QtCore.Qt.AutoText)
        self.labelLT2.setScaledContents(True)
        self.labelLT2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLT2.setObjectName("labelLT2")
        self.gridLayout_4.addWidget(self.labelLT2, 8, 4, 1, 1)
        self.labelCL4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCL4.sizePolicy().hasHeightForWidth())
        self.labelCL4.setSizePolicy(sizePolicy)
        self.labelCL4.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelCL4.setFont(font)
        self.labelCL4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelCL4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelCL4.setText("")
        self.labelCL4.setTextFormat(QtCore.Qt.AutoText)
        self.labelCL4.setScaledContents(True)
        self.labelCL4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCL4.setObjectName("labelCL4")
        self.gridLayout_4.addWidget(self.labelCL4, 6, 8, 1, 1)
        self.labelWT3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWT3.sizePolicy().hasHeightForWidth())
        self.labelWT3.setSizePolicy(sizePolicy)
        self.labelWT3.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelWT3.setFont(font)
        self.labelWT3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelWT3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelWT3.setText("")
        self.labelWT3.setTextFormat(QtCore.Qt.AutoText)
        self.labelWT3.setScaledContents(True)
        self.labelWT3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWT3.setObjectName("labelWT3")
        self.gridLayout_4.addWidget(self.labelWT3, 2, 2, 1, 1)
        self.labelLT6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLT6.sizePolicy().hasHeightForWidth())
        self.labelLT6.setSizePolicy(sizePolicy)
        self.labelLT6.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelLT6.setFont(font)
        self.labelLT6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelLT6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelLT6.setText("")
        self.labelLT6.setTextFormat(QtCore.Qt.AutoText)
        self.labelLT6.setScaledContents(True)
        self.labelLT6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLT6.setObjectName("labelLT6")
        self.gridLayout_4.addWidget(self.labelLT6, 9, 6, 1, 1)
        self.labelMK26 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMK26.sizePolicy().hasHeightForWidth())
        self.labelMK26.setSizePolicy(sizePolicy)
        self.labelMK26.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelMK26.setFont(font)
        self.labelMK26.setStyleSheet("background-color: rgb(148, 148, 148);\n"
"")
        self.labelMK26.setTextFormat(QtCore.Qt.RichText)
        self.labelMK26.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMK26.setObjectName("labelMK26")
        self.gridLayout_4.addWidget(self.labelMK26, 5, 6, 1, 1, QtCore.Qt.AlignLeft)
        self.labelWT4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelWT4.sizePolicy().hasHeightForWidth())
        self.labelWT4.setSizePolicy(sizePolicy)
        self.labelWT4.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelWT4.setFont(font)
        self.labelWT4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelWT4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelWT4.setText("")
        self.labelWT4.setTextFormat(QtCore.Qt.AutoText)
        self.labelWT4.setScaledContents(True)
        self.labelWT4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWT4.setObjectName("labelWT4")
        self.gridLayout_4.addWidget(self.labelWT4, 2, 6, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(80, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 2, 3, 1, 1)
        self.labelMK08 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMK08.sizePolicy().hasHeightForWidth())
        self.labelMK08.setSizePolicy(sizePolicy)
        self.labelMK08.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelMK08.setFont(font)
        self.labelMK08.setStyleSheet("background-color: rgb(148, 148, 148);")
        self.labelMK08.setTextFormat(QtCore.Qt.RichText)
        self.labelMK08.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMK08.setObjectName("labelMK08")
        self.gridLayout_4.addWidget(self.labelMK08, 5, 2, 1, 1, QtCore.Qt.AlignRight)
        self.labelCL1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCL1.sizePolicy().hasHeightForWidth())
        self.labelCL1.setSizePolicy(sizePolicy)
        self.labelCL1.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.labelCL1.setFont(font)
        self.labelCL1.setAutoFillBackground(False)
        self.labelCL1.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.labelCL1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.labelCL1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelCL1.setText("")
        self.labelCL1.setTextFormat(QtCore.Qt.AutoText)
        self.labelCL1.setScaledContents(True)
        self.labelCL1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCL1.setObjectName("labelCL1")
        self.gridLayout_4.addWidget(self.labelCL1, 5, 0, 1, 1)
        self.lcdTemp1 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdTemp1.sizePolicy().hasHeightForWidth())
        self.lcdTemp1.setSizePolicy(sizePolicy)
        self.lcdTemp1.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lcdTemp1.setFont(font)
        self.lcdTemp1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lcdTemp1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdTemp1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTemp1.setObjectName("lcdTemp1")
        self.gridLayout_4.addWidget(self.lcdTemp1, 0, 0, 1, 1)
        self.lcdPres1 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdPres1.sizePolicy().hasHeightForWidth())
        self.lcdPres1.setSizePolicy(sizePolicy)
        self.lcdPres1.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lcdPres1.setFont(font)
        self.lcdPres1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lcdPres1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdPres1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdPres1.setObjectName("lcdPres1")
        self.gridLayout_4.addWidget(self.lcdPres1, 3, 0, 1, 1)
        self.lcdTemp2 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdTemp2.sizePolicy().hasHeightForWidth())
        self.lcdTemp2.setSizePolicy(sizePolicy)
        self.lcdTemp2.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lcdTemp2.setFont(font)
        self.lcdTemp2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lcdTemp2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdTemp2.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdTemp2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTemp2.setObjectName("lcdTemp2")
        self.gridLayout_4.addWidget(self.lcdTemp2, 0, 8, 1, 1, QtCore.Qt.AlignRight)
        self.lcdPres2 = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdPres2.sizePolicy().hasHeightForWidth())
        self.lcdPres2.setSizePolicy(sizePolicy)
        self.lcdPres2.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lcdPres2.setFont(font)
        self.lcdPres2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lcdPres2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdPres2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdPres2.setObjectName("lcdPres2")
        self.gridLayout_4.addWidget(self.lcdPres2, 3, 8, 1, 1, QtCore.Qt.AlignRight)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnLT5 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLT5.sizePolicy().hasHeightForWidth())
        self.btnLT5.setSizePolicy(sizePolicy)
        self.btnLT5.setMinimumSize(QtCore.QSize(20, 30))
        self.btnLT5.setMaximumSize(QtCore.QSize(50, 50))
        self.btnLT5.setCheckable(False)
        self.btnLT5.setObjectName("btnLT5")
        self.gridLayout_2.addWidget(self.btnLT5, 10, 7, 1, 1)
        self.btnLT6 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLT6.sizePolicy().hasHeightForWidth())
        self.btnLT6.setSizePolicy(sizePolicy)
        self.btnLT6.setMinimumSize(QtCore.QSize(20, 30))
        self.btnLT6.setMaximumSize(QtCore.QSize(50, 50))
        self.btnLT6.setCheckable(False)
        self.btnLT6.setObjectName("btnLT6")
        self.gridLayout_2.addWidget(self.btnLT6, 10, 9, 1, 1)
        self.btnLT3 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLT3.sizePolicy().hasHeightForWidth())
        self.btnLT3.setSizePolicy(sizePolicy)
        self.btnLT3.setMinimumSize(QtCore.QSize(20, 30))
        self.btnLT3.setMaximumSize(QtCore.QSize(50, 50))
        self.btnLT3.setCheckable(False)
        self.btnLT3.setObjectName("btnLT3")
        self.gridLayout_2.addWidget(self.btnLT3, 9, 9, 1, 1)
        self.btnWind4 = QtWidgets.QToolButton(self.centralwidget)
        self.btnWind4.setMinimumSize(QtCore.QSize(20, 25))
        self.btnWind4.setMaximumSize(QtCore.QSize(50, 50))
        self.btnWind4.setCheckable(False)
        self.btnWind4.setObjectName("btnWind4")
        self.gridLayout_2.addWidget(self.btnWind4, 3, 9, 1, 1)
        self.lineCL1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineCL1.sizePolicy().hasHeightForWidth())
        self.lineCL1.setSizePolicy(sizePolicy)
        self.lineCL1.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineCL1.setFont(font)
        self.lineCL1.setText("")
        self.lineCL1.setObjectName("lineCL1")
        self.gridLayout_2.addWidget(self.lineCL1, 5, 1, 1, 1)
        self.lineLT2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineLT2.sizePolicy().hasHeightForWidth())
        self.lineLT2.setSizePolicy(sizePolicy)
        self.lineLT2.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineLT2.setFont(font)
        self.lineLT2.setText("")
        self.lineLT2.setObjectName("lineLT2")
        self.gridLayout_2.addWidget(self.lineLT2, 9, 6, 1, 1)
        self.lineWT2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineWT2.sizePolicy().hasHeightForWidth())
        self.lineWT2.setSizePolicy(sizePolicy)
        self.lineWT2.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineWT2.setFont(font)
        self.lineWT2.setText("")
        self.lineWT2.setObjectName("lineWT2")
        self.gridLayout_2.addWidget(self.lineWT2, 1, 8, 1, 1)
        self.lineWT1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineWT1.sizePolicy().hasHeightForWidth())
        self.lineWT1.setSizePolicy(sizePolicy)
        self.lineWT1.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineWT1.setFont(font)
        self.lineWT1.setText("")
        self.lineWT1.setObjectName("lineWT1")
        self.gridLayout_2.addWidget(self.lineWT1, 1, 4, 1, 1)
        self.lineWT3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineWT3.sizePolicy().hasHeightForWidth())
        self.lineWT3.setSizePolicy(sizePolicy)
        self.lineWT3.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineWT3.setFont(font)
        self.lineWT3.setText("")
        self.lineWT3.setObjectName("lineWT3")
        self.gridLayout_2.addWidget(self.lineWT3, 3, 4, 1, 1)
        self.lineLT4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineLT4.sizePolicy().hasHeightForWidth())
        self.lineLT4.setSizePolicy(sizePolicy)
        self.lineLT4.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineLT4.setFont(font)
        self.lineLT4.setText("")
        self.lineLT4.setObjectName("lineLT4")
        self.gridLayout_2.addWidget(self.lineLT4, 10, 4, 1, 1)
        self.lineLT1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineLT1.sizePolicy().hasHeightForWidth())
        self.lineLT1.setSizePolicy(sizePolicy)
        self.lineLT1.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineLT1.setFont(font)
        self.lineLT1.setText("")
        self.lineLT1.setObjectName("lineLT1")
        self.gridLayout_2.addWidget(self.lineLT1, 9, 4, 1, 1)
        self.lineWT4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineWT4.sizePolicy().hasHeightForWidth())
        self.lineWT4.setSizePolicy(sizePolicy)
        self.lineWT4.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineWT4.setFont(font)
        self.lineWT4.setText("")
        self.lineWT4.setObjectName("lineWT4")
        self.gridLayout_2.addWidget(self.lineWT4, 3, 8, 1, 1)
        self.lineLT3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineLT3.sizePolicy().hasHeightForWidth())
        self.lineLT3.setSizePolicy(sizePolicy)
        self.lineLT3.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineLT3.setFont(font)
        self.lineLT3.setText("")
        self.lineLT3.setObjectName("lineLT3")
        self.gridLayout_2.addWidget(self.lineLT3, 9, 8, 1, 1)
        self.lineLT5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineLT5.sizePolicy().hasHeightForWidth())
        self.lineLT5.setSizePolicy(sizePolicy)
        self.lineLT5.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineLT5.setFont(font)
        self.lineLT5.setText("")
        self.lineLT5.setObjectName("lineLT5")
        self.gridLayout_2.addWidget(self.lineLT5, 10, 6, 1, 1)
        self.lineLT6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineLT6.sizePolicy().hasHeightForWidth())
        self.lineLT6.setSizePolicy(sizePolicy)
        self.lineLT6.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineLT6.setFont(font)
        self.lineLT6.setText("")
        self.lineLT6.setObjectName("lineLT6")
        self.gridLayout_2.addWidget(self.lineLT6, 10, 8, 1, 1)
        self.btnLT1 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLT1.sizePolicy().hasHeightForWidth())
        self.btnLT1.setSizePolicy(sizePolicy)
        self.btnLT1.setMinimumSize(QtCore.QSize(20, 30))
        self.btnLT1.setMaximumSize(QtCore.QSize(50, 50))
        self.btnLT1.setCheckable(False)
        self.btnLT1.setObjectName("btnLT1")
        self.gridLayout_2.addWidget(self.btnLT1, 9, 3, 1, 1)
        self.btnCL2 = QtWidgets.QToolButton(self.centralwidget)
        self.btnCL2.setMinimumSize(QtCore.QSize(20, 25))
        self.btnCL2.setMaximumSize(QtCore.QSize(50, 50))
        self.btnCL2.setCheckable(False)
        self.btnCL2.setObjectName("btnCL2")
        self.gridLayout_2.addWidget(self.btnCL2, 5, 11, 1, 1)
        self.btnCL3 = QtWidgets.QToolButton(self.centralwidget)
        self.btnCL3.setMinimumSize(QtCore.QSize(20, 25))
        self.btnCL3.setMaximumSize(QtCore.QSize(50, 50))
        self.btnCL3.setCheckable(False)
        self.btnCL3.setObjectName("btnCL3")
        self.gridLayout_2.addWidget(self.btnCL3, 6, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 8, 1, 1, 10)
        self.btnCL4 = QtWidgets.QToolButton(self.centralwidget)
        self.btnCL4.setMinimumSize(QtCore.QSize(20, 25))
        self.btnCL4.setMaximumSize(QtCore.QSize(50, 50))
        self.btnCL4.setCheckable(False)
        self.btnCL4.setObjectName("btnCL4")
        self.gridLayout_2.addWidget(self.btnCL4, 6, 11, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 4, 1, 1, 11)
        spacerItem11 = QtWidgets.QSpacerItem(80, 60, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 1, 1, 11)
        self.btnLT2 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLT2.sizePolicy().hasHeightForWidth())
        self.btnLT2.setSizePolicy(sizePolicy)
        self.btnLT2.setMinimumSize(QtCore.QSize(20, 30))
        self.btnLT2.setMaximumSize(QtCore.QSize(50, 50))
        self.btnLT2.setCheckable(False)
        self.btnLT2.setObjectName("btnLT2")
        self.gridLayout_2.addWidget(self.btnLT2, 9, 7, 1, 1)
        self.btnWind1 = QtWidgets.QToolButton(self.centralwidget)
        self.btnWind1.setMinimumSize(QtCore.QSize(20, 25))
        self.btnWind1.setMaximumSize(QtCore.QSize(50, 50))
        self.btnWind1.setCheckable(False)
        self.btnWind1.setChecked(False)
        self.btnWind1.setObjectName("btnWind1")
        self.gridLayout_2.addWidget(self.btnWind1, 1, 3, 1, 1)
        self.btnCL1 = QtWidgets.QToolButton(self.centralwidget)
        self.btnCL1.setMinimumSize(QtCore.QSize(20, 25))
        self.btnCL1.setMaximumSize(QtCore.QSize(50, 50))
        self.btnCL1.setCheckable(False)
        self.btnCL1.setObjectName("btnCL1")
        self.gridLayout_2.addWidget(self.btnCL1, 5, 0, 1, 1)
        self.btnWind3 = QtWidgets.QToolButton(self.centralwidget)
        self.btnWind3.setMinimumSize(QtCore.QSize(20, 25))
        self.btnWind3.setMaximumSize(QtCore.QSize(50, 50))
        self.btnWind3.setCheckable(False)
        self.btnWind3.setObjectName("btnWind3")
        self.gridLayout_2.addWidget(self.btnWind3, 3, 3, 1, 1)
        self.btnLT4 = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLT4.sizePolicy().hasHeightForWidth())
        self.btnLT4.setSizePolicy(sizePolicy)
        self.btnLT4.setMinimumSize(QtCore.QSize(20, 30))
        self.btnLT4.setMaximumSize(QtCore.QSize(50, 50))
        self.btnLT4.setCheckable(False)
        self.btnLT4.setObjectName("btnLT4")
        self.gridLayout_2.addWidget(self.btnLT4, 10, 3, 1, 1)
        self.lineCL3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineCL3.sizePolicy().hasHeightForWidth())
        self.lineCL3.setSizePolicy(sizePolicy)
        self.lineCL3.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineCL3.setFont(font)
        self.lineCL3.setText("")
        self.lineCL3.setObjectName("lineCL3")
        self.gridLayout_2.addWidget(self.lineCL3, 6, 1, 1, 1)
        self.lineCL2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineCL2.sizePolicy().hasHeightForWidth())
        self.lineCL2.setSizePolicy(sizePolicy)
        self.lineCL2.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineCL2.setFont(font)
        self.lineCL2.setText("")
        self.lineCL2.setObjectName("lineCL2")
        self.gridLayout_2.addWidget(self.lineCL2, 5, 10, 1, 1)
        self.btnWind2 = QtWidgets.QToolButton(self.centralwidget)
        self.btnWind2.setMinimumSize(QtCore.QSize(20, 25))
        self.btnWind2.setMaximumSize(QtCore.QSize(50, 50))
        self.btnWind2.setCheckable(False)
        self.btnWind2.setObjectName("btnWind2")
        self.gridLayout_2.addWidget(self.btnWind2, 1, 9, 1, 1)
        self.lineCL4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineCL4.sizePolicy().hasHeightForWidth())
        self.lineCL4.setSizePolicy(sizePolicy)
        self.lineCL4.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineCL4.setFont(font)
        self.lineCL4.setText("")
        self.lineCL4.setObjectName("lineCL4")
        self.gridLayout_2.addWidget(self.lineCL4, 6, 10, 1, 1)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_2)
        spacerItem12 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.SpanningRole, spacerItem12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.statusBar.setFont(font)
        self.statusBar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.statusBar.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.statusBar.setStatusTip("")
        self.statusBar.setWhatsThis("")
        self.statusBar.setAccessibleName("")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1106, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menuSett = QtWidgets.QMenu(self.menu)
        self.menuSett.setObjectName("menuSett")
        self.menuLOGS = QtWidgets.QMenu(self.menu)
        self.menuLOGS.setObjectName("menuLOGS")
        MainWindow.setMenuBar(self.menuBar)
        self.iram = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/icons8-settings-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iram.setIcon(icon1)
        self.iram.setObjectName("iram")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.report = QtWidgets.QAction(MainWindow)
        self.report.setObjectName("report")
        self.log = QtWidgets.QAction(MainWindow)
        self.log.setObjectName("log")
        self.menuSett.addAction(self.iram)
        self.menuLOGS.addAction(self.report)
        self.menuLOGS.addAction(self.log)
        self.menu.addAction(self.menuSett.menuAction())
        self.menu.addAction(self.menuLOGS.menuAction())
        self.menu.addAction(self.about)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Maintenance"))
        self.btn.setText(_translate("MainWindow", "M"))
        self.terminal.setText(_translate("MainWindow", "TERMINAL"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.labelMK26.setText(_translate("MainWindow", "MK302"))
        self.labelMK08.setText(_translate("MainWindow", "MK122"))
        self.btnLT5.setText(_translate("MainWindow", "M"))
        self.btnLT6.setText(_translate("MainWindow", "M"))
        self.btnLT3.setText(_translate("MainWindow", "M"))
        self.btnWind4.setText(_translate("MainWindow", "M"))
        self.btnLT1.setText(_translate("MainWindow", "M"))
        self.btnCL2.setText(_translate("MainWindow", "M"))
        self.btnCL3.setText(_translate("MainWindow", "M"))
        self.btnCL4.setText(_translate("MainWindow", "M"))
        self.btnLT2.setText(_translate("MainWindow", "M"))
        self.btnWind1.setText(_translate("MainWindow", "M"))
        self.btnCL1.setText(_translate("MainWindow", "M"))
        self.btnWind3.setText(_translate("MainWindow", "M"))
        self.btnLT4.setText(_translate("MainWindow", "M"))
        self.btnWind2.setText(_translate("MainWindow", "M"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.menuSett.setTitle(_translate("MainWindow", "Настройки"))
        self.menuLOGS.setTitle(_translate("MainWindow", "LOGS"))
        self.iram.setText(_translate("MainWindow", "IRAM"))
        self.about.setText(_translate("MainWindow", "About"))
        self.report.setText(_translate("MainWindow", "Report"))
        self.log.setText(_translate("MainWindow", "Log"))


