# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(643, 746)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icons8-settings-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        Settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalLayoutWidget = QtWidgets.QWidget(Settings)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 20, 511, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.boxSensors = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxSensors.sizePolicy().hasHeightForWidth())
        self.boxSensors.setSizePolicy(sizePolicy)
        self.boxSensors.setObjectName("boxSensors")
        self.gridLayout.addWidget(self.boxSensors, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(150, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setMaximumSize(QtCore.QSize(500, 30))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.lineIRAM = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineIRAM.setMinimumSize(QtCore.QSize(0, 15))
        self.lineIRAM.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineIRAM.setObjectName("lineIRAM")
        self.gridLayout.addWidget(self.lineIRAM, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.checkRepW = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkRepW.setMinimumSize(QtCore.QSize(0, 15))
        self.checkRepW.setText("")
        self.checkRepW.setObjectName("checkRepW")
        self.gridLayout.addWidget(self.checkRepW, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.lineFileT = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineFileT.setMinimumSize(QtCore.QSize(0, 15))
        self.lineFileT.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineFileT.setObjectName("lineFileT")
        self.gridLayout.addWidget(self.lineFileT, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineSND = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineSND.setMinimumSize(QtCore.QSize(0, 15))
        self.lineSND.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineSND.setObjectName("lineSND")
        self.gridLayout.addWidget(self.lineSND, 1, 1, 1, 1)
        self.lineTimer = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineTimer.setMinimumSize(QtCore.QSize(0, 15))
        self.lineTimer.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineTimer.setObjectName("lineTimer")
        self.gridLayout.addWidget(self.lineTimer, 3, 1, 1, 1)
        self.checkLogW = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkLogW.setMinimumSize(QtCore.QSize(0, 15))
        self.checkLogW.setText("")
        self.checkLogW.setObjectName("checkLogW")
        self.gridLayout.addWidget(self.checkLogW, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineSensors = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineSensors.setMinimumSize(QtCore.QSize(0, 15))
        self.lineSensors.setObjectName("lineSensors")
        self.horizontalLayout_2.addWidget(self.lineSensors)
        spacerItem = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttSensors = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttSensors.setObjectName("buttSensors")
        self.horizontalLayout_2.addWidget(self.buttSensors)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.viewSensors = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewSensors.setFont(font)
        self.viewSensors.setObjectName("viewSensors")
        self.horizontalLayout_3.addWidget(self.viewSensors)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 1, 1, 1)
        self.buttOK = QtWidgets.QDialogButtonBox(Settings)
        self.buttOK.setGeometry(QtCore.QRect(410, 690, 156, 23))
        self.buttOK.setFocusPolicy(QtCore.Qt.TabFocus)
        self.buttOK.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttOK.setCenterButtons(False)
        self.buttOK.setObjectName("buttOK")

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)
        Settings.setTabOrder(self.buttOK, self.lineIRAM)
        Settings.setTabOrder(self.lineIRAM, self.lineSND)
        Settings.setTabOrder(self.lineSND, self.lineFileT)
        Settings.setTabOrder(self.lineFileT, self.lineTimer)
        Settings.setTabOrder(self.lineTimer, self.checkRepW)
        Settings.setTabOrder(self.checkRepW, self.checkLogW)
        Settings.setTabOrder(self.checkLogW, self.boxSensors)
        Settings.setTabOrder(self.boxSensors, self.lineSensors)
        Settings.setTabOrder(self.lineSensors, self.buttSensors)
        Settings.setTabOrder(self.buttSensors, self.viewSensors)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Настройки"))
        self.label_7.setText(_translate("Settings", "Время обновления опроса"))
        self.label.setText(_translate("Settings", "Путь к папке IRAM"))
        self.label_2.setText(_translate("Settings", "Путь к WAV файлу"))
        self.label_5.setText(_translate("Settings", "Запись Report файла"))
        self.label_3.setText(_translate("Settings", "Время ожидания файла"))
        self.label_6.setText(_translate("Settings", "Запись LOG файла"))
        self.buttSensors.setText(_translate("Settings", "Добавить"))


