# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(529, 428)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icons8-settings-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        Settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.verticalLayoutWidget = QtWidgets.QWidget(Settings)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 0, 511, 212))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setMaximumSize(QtCore.QSize(500, 30))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setMinimumSize(QtCore.QSize(0, 15))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 4, 1, 1, 1)
        self.repWrite = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.repWrite.setMinimumSize(QtCore.QSize(0, 15))
        self.repWrite.setText("")
        self.repWrite.setObjectName("repWrite")
        self.gridLayout.addWidget(self.repWrite, 5, 1, 1, 1)
        self.lineIRAM = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineIRAM.setMinimumSize(QtCore.QSize(0, 15))
        self.lineIRAM.setObjectName("lineIRAM")
        self.gridLayout.addWidget(self.lineIRAM, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineSND = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineSND.setMinimumSize(QtCore.QSize(0, 15))
        self.lineSND.setObjectName("lineSND")
        self.gridLayout.addWidget(self.lineSND, 1, 1, 1, 1)
        self.lineFileT = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineFileT.setMinimumSize(QtCore.QSize(0, 15))
        self.lineFileT.setObjectName("lineFileT")
        self.gridLayout.addWidget(self.lineFileT, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(150, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.logWrite = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.logWrite.setMinimumSize(QtCore.QSize(0, 15))
        self.logWrite.setText("")
        self.logWrite.setObjectName("logWrite")
        self.gridLayout.addWidget(self.logWrite, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.lineTimer = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineTimer.setMinimumSize(QtCore.QSize(0, 15))
        self.lineTimer.setObjectName("lineTimer")
        self.gridLayout.addWidget(self.lineTimer, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(150, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.buttonOK = QtWidgets.QDialogButtonBox(Settings)
        self.buttonOK.setGeometry(QtCore.QRect(360, 370, 156, 23))
        self.buttonOK.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonOK.setObjectName("buttonOK")

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Настройки"))
        self.label.setText(_translate("Settings", "Путь к папке IRAM"))
        self.label_2.setText(_translate("Settings", "Путь к WAV файлу"))
        self.label_3.setText(_translate("Settings", "Время ожидания файла"))
        self.label_5.setText(_translate("Settings", "Запись Report файла"))
        self.label_6.setText(_translate("Settings", "Запись LOG файла"))
        self.label_7.setText(_translate("Settings", "Время обновления опроса"))


