# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Weather_design.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 711)
        MainWindow.setMaximumSize(QtCore.QSize(1107, 711))
        MainWindow.setStyleSheet("background-color: rgb(88, 133, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(170, 160, 814, 258))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.wt2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.wt2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wt2.sizePolicy().hasHeightForWidth())
        self.wt2.setSizePolicy(sizePolicy)
        self.wt2.setMinimumSize(QtCore.QSize(350, 50))
        self.wt2.setMaximumSize(QtCore.QSize(450, 70))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.wt2.setFont(font)
        self.wt2.setStyleSheet("background-color: qconicalgradient(cx:0.079, cy:1, angle:0, stop:0 rgba(54, 164, 255, 174), stop:1 rgba(255, 255, 255, 255));")
        self.wt2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wt2.setAlignment(QtCore.Qt.AlignCenter)
        self.wt2.setObjectName("wt2")
        self.gridLayout.addWidget(self.wt2, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 2, 1, 1)
        self.cl1 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cl1.sizePolicy().hasHeightForWidth())
        self.cl1.setSizePolicy(sizePolicy)
        self.cl1.setMinimumSize(QtCore.QSize(350, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.cl1.setFont(font)
        self.cl1.setStyleSheet("background-color: qconicalgradient(cx:0.079, cy:1, angle:0, stop:0 rgba(54, 164, 255, 174), stop:1 rgba(255, 255, 255, 255));")
        self.cl1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cl1.setAlignment(QtCore.Qt.AlignCenter)
        self.cl1.setObjectName("cl1")
        self.gridLayout.addWidget(self.cl1, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_1.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.wt1 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wt1.sizePolicy().hasHeightForWidth())
        self.wt1.setSizePolicy(sizePolicy)
        self.wt1.setMinimumSize(QtCore.QSize(350, 50))
        self.wt1.setMaximumSize(QtCore.QSize(450, 70))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.wt1.setFont(font)
        self.wt1.setStyleSheet("background-color: qconicalgradient(cx:0.079, cy:1, angle:0, stop:0 rgba(54, 164, 255, 174), stop:1 rgba(255, 255, 255, 255));")
        self.wt1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wt1.setAlignment(QtCore.Qt.AlignCenter)
        self.wt1.setObjectName("wt1")
        self.gridLayout.addWidget(self.wt1, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather"))
        self.wt2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", " DDD                       FF"))
        self.cl1.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Ветер"))
        self.label_1.setText(_translate("MainWindow", "Облачность"))
        self.wt1.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", " DDD                       FF"))


